--아까 집어넣었던 데이터베이스들 출력
SELECT * FROM STUDENT;

--학생들의 키 순서 역순
SELECT * FROM STUDENT ORDER BY HEIGHT DESC;

--학생들의 인원수, 평균키, 평균 몸무게
SELECT COUNT(*), AVG(HEIGHT),  AVG(WEIGHT) fROM STUDENT;

--학과별 학생들의 인원수, 평균키, 평균, 몸무게
SELECT DEPTNO, COUNT(*), AVG(HEIGHT),  AVG(WEIGHT) fROM STUDENT GROUP BY DEPTNO;


SELECT * FROM PROFESSOR;
SELECT * FROM DEPARTMENT; 
SELECT * FROM SALGRADE; 

--헬로월드 출력
SELECT 'HELLO WORLD' FROM DUAL;

--학생의 학번, 이름, 학과이름을 조회
--SELECT STUDNO, NAME, DNAME
--FROM STUDENT
--NATURAL JOIN DEPARTMENT;

SELECT STUDNO, NAME, DNAME
FROM STUDENT S, DEPARTMENT D
WHERE S.DEPTNO = D.DEPTNO;

SELECT STUDNO, NAME, (SELECT DNAME FROM DEPARTMENT D WHERE D.DEPTNO = S.DEPTNO) AS DNAME
FROM STUDENT S;


--현재 접속할 데이터베이스 계정에서 생성된 모든 테이블 입력
SELECT * FROM TAB;


