--DBMS_XDB.SETHTTPPORT SETTER 역할 << 프로시저
--DBMS_XDB.GETHTTPPORT GETTER 역할 << 함수

SELECT DBMS_XDB.GETHTTPPORT FROM DUAL;

EXEC DBMS_XDB.SETHTTPPORT(9090);

SELECT * FROM JOBS;

--프로시저선언
--프로시저명 MYSETHTTPPORT
--매개변수 IN , NUMBER타입
--매개변수로 PORT값 변경

CREATE OR REPLACE PROCEDURE MYSETHTTPPORT
(
    P_N NUMBER := 10000
)
IS
BEGIN
    DBMS_XDB.SETHTTPPORT(P_N);
END;
/



        
